name: Publish Docker image

on: 
  push:
    branches:
      - 'main'
      - 'ci'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu' # Alternative distribution options are available.
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: aldeeyar/innometrics-eureka

      - name: /[Eureka/] Build JAR file
        working-directory: ./eureka-server
        run: |
          chmod +x mvnw
          ./mvnw clean install

      - name: /[Auth/] Build JAR file
        working-directory: ./auth-server
        run: |
          chmod +x mvnw
          ./mvnw clean install

      - name: /[Config/] Build JAR file
        working-directory: ./config-service
        run: |
          chmod +x mvnw
          ./mvnw clean install
          
      - name: /[Collector/] Build JAR file
        working-directory: ./activities-collector
        run: |
          chmod +x mvnw
          ./mvnw clean install

      - name: /[API/] Build JAR file
        working-directory: ./InnoMetrics-RestAPI
        run: |
          chmod +x mvnw
          ./mvnw clean install
          
      - name: /[Agents/] Build JAR file
        working-directory: ./agents-gateway
        run: |
          chmod +x mvnw
          ./mvnw clean install
      
      - name: /[Eureka/] Push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./eureka-server/Dockerfile
          push: true
          tags: aldeeyar/innometrics-eureka:latest
          build-args: |
            JAR_FILE=./eureka-server/target/innometrics-eureka-server.jar

      - name: /[Auth/] Push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./auth-server/Dockerfile
          push: true
          tags: aldeeyar/innometrics-auth:latest
          build-args: |
            JAR_FILE=./auth-server/target/innometrics-auth-server.jar

      - name: /[Config/] Push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./config-service/Dockerfile
          push: true
          tags: aldeeyar/innometrics-config:latest
          build-args: |
            JAR_FILE=./config-service/target/innometrics-config-service.jar

      - name: /[Collector/] Push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./activities-collector/Dockerfile
          push: true
          tags: aldeeyar/innometrics-collector:latest
          build-args: |
            JAR_FILE=./activities-collector/target/InnoMetrics-Collector-Server.jar

      - name: /[API/] Push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./InnoMetrics-RestAPI/Dockerfile
          push: true
          tags: aldeeyar/innometrics-api:latest
          build-args: |
            JAR_FILE=./InnoMetrics-RestAPI/target/InnoMetrics-RestAPI.jar

      - name: /[Agents/] Push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./agents-gateway/Dockerfile
          push: true
          tags: aldeeyar/innometrics-agents:latest
          build-args: |
            JAR_FILE=./agents-gateway/target/InnoMetrics-Agents-gateway.jar